export const CarListData = [
  {
    id: 1,
    name: "Uber X",
    seat: 4,
    desc: "Affordable,Everydat rides",
    amount: 1.1,
    images: "./car_orange.png",
  },
  {
    id: 2,
    name: "Comfort",
    seat: 4,
    desc: "New Cars with extra legroom",
    amount: 1.6,
    images: "./car_black.png",
  },
  {
    id: 3,
    name: "Rapido ",
    seat: 5,
    desc: "fast and clen",
    amount: 1.4,
    images: "./bike_white.png",
  },
  {
    id: 4,
    name: "Zomato ",
    seat: 3,
    desc: "fast and clen",
    amount: 1.4,
    images: "./bike_orange.png",
  },
  {
    id: 5,
    name: "Comfort",
    seat: 4,
    desc: "New Cars with extra legroom",
    amount: 1.6,
    images: "./car_black.png",
  },
];
